
name: 'rewards_dbt'
version: '1.0.0'
profile: 'rewards_dbt'

quoting:
  database: false
  schema: false
  identifier: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  rewards_dbt:
    core:
      schema: core
      materialized: table

tests:
  rewards_dbt:
    +severity: warn
